version: '3'
services:
  db:
    image: bitnami/mongodb:5.0.17
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: 123456
      MONGODB_DATABASE: nest
    ports:
      - "27017:27017"
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  mongodb_data:
    driver: local